namespace MyHttpServer.Core.ContentTypes;

public static class MimeTypeMap
{
    public const string Default = "application/octet-stream";

    public static IReadOnlyDictionary<string, string> Map { get; } =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            [".html"] = "text/html",
            [".htm"] = "text/html",
            [".xhtml"] = "application/xhtml+xml",
            [".css"] = "text/css",
            [".csv"] = "text/csv",
            [".ics"] = "text/calendar",
            [".txt"] = "text/plain",
            [".md"] = "text/markdown",
            [".js"] = "text/javascript",
            [".mjs"] = "text/javascript",
            [".json"] = "application/json",
            [".jsonld"] = "application/ld+json",
            [".map"] = "application/json",
            [".webmanifest"] = "application/manifest+json",
            [".xml"] = "application/xml",
            [".xul"] = "application/vnd.mozilla.xul+xml",
            [".rtf"] = "application/rtf",
            [".php"] = "application/x-httpd-php",
            [".sh"] = "application/x-sh",
            [".csh"] = "application/x-csh",
            [".ts"] = "video/mp2t",

            [".png"] = "image/png",
            [".jpg"] = "image/jpeg",
            [".jpeg"] = "image/jpeg",
            [".gif"] = "image/gif",
            [".bmp"] = "image/bmp",
            [".webp"] = "image/webp",
            [".avif"] = "image/avif",
            [".apng"] = "image/apng",
            [".svg"] = "image/svg+xml",
            [".ico"] = "image/vnd.microsoft.icon",
            [".tif"] = "image/tiff",
            [".tiff"] = "image/tiff",

            [".woff"] = "font/woff",
            [".woff2"] = "font/woff2",
            [".ttf"] = "font/ttf",
            [".otf"] = "font/otf",
            [".eot"] = "application/vnd.ms-fontobject",

            [".aac"] = "audio/aac",
            [".mp3"] = "audio/mpeg",
            [".wav"] = "audio/wav",
            [".weba"] = "audio/webm",
            [".oga"] = "audio/ogg",
            [".opus"] = "audio/ogg",
            [".mid"] = "audio/midi",
            [".midi"] = "audio/midi",
            [".cda"] = "application/x-cdf",

            [".mp4"] = "video/mp4",
            [".mpeg"] = "video/mpeg",
            [".webm"] = "video/webm",
            [".ogv"] = "video/ogg",
            [".avi"] = "video/x-msvideo",
            [".3gp"] = "video/3gpp",
            [".3g2"] = "video/3gpp2",
            [".ogx"] = "application/ogg",

            [".pdf"] = "application/pdf",
            [".doc"] = "application/msword",
            [".docx"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            [".xls"] = "application/vnd.ms-excel",
            [".xlsx"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            [".ppt"] = "application/vnd.ms-powerpoint",
            [".pptx"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            [".odt"] = "application/vnd.oasis.opendocument.text",
            [".ods"] = "application/vnd.oasis.opendocument.spreadsheet",
            [".odp"] = "application/vnd.oasis.opendocument.presentation",
            [".vsd"] = "application/vnd.visio",
            [".abw"] = "application/x-abiword",
            [".azw"] = "application/vnd.amazon.ebook",
            [".epub"] = "application/epub+zip",
            [".mpkg"] = "application/vnd.apple.installer+xml",

            [".zip"] = "application/zip",
            [".7z"] = "application/x-7z-compressed",
            [".rar"] = "application/vnd.rar",
            [".tar"] = "application/x-tar",
            [".gz"] = "application/gzip",
            [".bz"] = "application/x-bzip",
            [".bz2"] = "application/x-bzip2",
            [".arc"] = "application/x-freearc",
            [".jar"] = "application/java-archive",
            [".bin"] = "application/octet-stream",
            [".wasm"] = "application/wasm",
        };
}
